### ISSUE TITLE
General repair and preparation for RHEL8 + newer versions

### ISSUE THREAD

**Issue by Dzordzu** [lvps/389ds-replication#4]
# Original issue
389ds-server has already fixed this issue, but in this repo it persists

## Error

```
community.general.ldap_attr has been removed
```

## Solution

Move ldap_attr to ldap_attrs

## OP help

U̶n̶f̶o̶r̶t̶u̶n̶e̶t̶e̶l̶l̶y̶ ̶-̶ ̶v̶e̶r̶y̶ ̶u̶n̶l̶i̶k̶e̶l̶y̶
Yep

# Issue

Role:
1. contains a few issues (ansible has changed some integrated roles) 
2. does not work for RHEL8 and newer

**Comment by lvps** [comment]
Yep, that's the solution. I didn't do it sooner because ldap_attr was deprecated and removed very quickly, so some Linux distros still provided an old Ansible version without ldap_attrs, while others already provide a new version without ldap_attr. I didn't want to break compatibility immediately.

I guess it's time to update now, though. It shouldn't be too complicated if you want to send a PR, or I'll do it within a few days.

**Comment by Dzordzu** [comment]
Yep. I'm working on it, and - to be honest - there are more bugs, than I expected

**Comment by lvps** [comment]
I've also noticed that another user already did that change: https://github.com/Mr-Goldlog/ldap_389ds_replication/commit/2018ab704ae2e390e7a5a499f63bd28368bd6cd2

I tried asking for a pull request, but no reply yet... I guess we could just copy that code and attribute it to the author, the license is still the same. However I haven't tested it, so I don't know if there are more bugs there.

**Comment by lvps** [comment]
I've pushed the necessary changes, but I couldn't test them.
@Dzordzu could you check if this works for you? Which kind of other bugs were you mentioning?

Testing it should be relatively simple, e.g. running one of the examples from https://github.com/lvps/389ds-examples, but right now I don't have a computer capable of running Vagrant (it's ridiculous, I know)..

**Comment by Dzordzu** [comment]
Hi. I've done similar changes, and also fixed a few other issues. You can check it out https://github.com/Dzordzu/389ds-replication
I will make a PR after resolving one more issue with replica initialization
Also - when using multimaster with more nodes there is an issue with 389ds that kills dirsrv@default (cause the root dn is not maching) - it needs to be fixed, but dunno - as of now - how

**Comment by lvps** [comment]
Thanks for all those updates and fixes, I checked your fork and it looks good. However, I have 2 questions:

1. Did the "TLS"  value cause problems in https://github.com/Dzordzu/389ds-replication/commit/3691b93c6a6b94d2cb0dcee67be3267594af6069 ? IIRC my idea was to always encrypt traffic, either with LDAPS or StartTLS. If there's a risk this could send replication data unencrypted I'm not really sure what to do, maybe add another option to choose between StartTLS and unencrypted?
2. Which 389DS or RHEL (or clones) did you test your changes on? I suspect some of the things you updated are correct for recent 389DS versions (RHEL8), but the old behavior may still be needed in older versions (RHEL7)

**Comment by Dzordzu** [comment]
> Did the "TLS" value cause problems in Dzordzu@3691b93

I had some issues with certificates (I'm using LE with certbot and unfortunatelly verification fails). Both TLS and LDAPS were failing. What's more in newer versions, at least in the cockpit, I could not find TLS option. It was causing loads of issues, and (in my case) communication via pure LDAP is secure enough. I've got a separate private network for replication

>  If there's a risk this could send replication data unencrypted I'm not really sure what to do, maybe add another option to choose between StartTLS and unencrypted

Another option seems fine. Although, if it's done that way, we would have to split that into three different tasks for clarity

> Which 389DS or RHEL (or clones) did you test your changes on

Alma Linux (RHEL8). It's one of the newest versions of the 389ds. That's why changelog5 entry has to be removed. If you wish, there can be a changelog configuration, but now it's [integrated into db backend](https://directory.fedoraproject.org/docs/389ds/design/integrate-changelog-database-and-backend-database.html)

**Comment by Dzordzu** [comment]
Furthermore RHEL7 and Centos7 support will be dropped very soon. I don't know if there is a reason to maintain another options just for backward compatibility

**Comment by lvps** [comment]
Thanks again for taking the time to do these updates.
On the TLS issue, that makes sense but I'd still leave TLS/LDAPS as the default: I for example have severs on the public Internet and I don't want other people with a similar setup to shoot themselves in the foot, as the saying goes.
Even without splitting the task, I think it should be very easy to introduce a new variable like `dirsrv_replica_transport` and make the default value `"{{ 'LDAPS' if ( dirsrv_consumer_uri | urlsplit('scheme') | lower ) == 'ldaps' else 'TLS' }}"`, or just `LDAPS`, or none and fail the task if the value is not set. So it can be set to any value by users, but the default is never potentially insecure.

I should also investigate why `TLS` doesn't  work for newer versions but I don't have time right now... At least it works for older ones, which is something.

On the changelog issue, it seems the change was done in 389ds 1.4.x (see milestone in https://github.com/389ds/389-ds-base/issues/2621), while RHEL7 and clones are still on 1.3.x and I don't think they will ever be upgraded.
While CentOS 7 is EOL, as far as I understand RHEL7 is supported until 2024 (and clones will follow that schedule, presumably). Nobody is using it for new installs, but it's still definitely around in production and it will be for a while.

Users could just use an older version of this role, but to make things easier could you just add a check like https://github.com/lvps/389ds-server/blob/b38d485545dd14b39250cc0ed6fca7c47b7293ca/tasks/install_389ds.yml#L3 or https://github.com/lvps/389ds-server/blob/b38d485545dd14b39250cc0ed6fca7c47b7293ca/tasks/install_389ds.yml#L10 and add the changelog attribute for older 389ds versions?

Making these small changes and fixing the "root dn is not matching" issue should be enough to cover both old and new installs, so for me it's good for a pull request. However I also have no idea how to fix the root dn issue, unfortunately. I'm sorry I cannot really help with that one.

**Comment by rgroux** [comment]
Hello guys, 

i did 2 PR
 - #5 for the `dirsrv_uri` and
 - #6 for the `ldap_attrs`

This is not perfect, but the role is ok, and functional and can be call from your ansible code 
and at the end you have to start synchronisation from supplier to consumers, with something like that

```yaml
    # Start sync
    - name: init replication
      community.general.ldap_attrs:
        server_uri: "ldap://localhost/"
        bind_dn: "{{ dirsrv_rootdn }}"
        bind_pw: "{{ dirsrv_rootdn_password }}"
        dn: "cn=agreement_with_{{ consumer }},cn=replica,cn=\"{{ dirsrv_suffix }}\",cn=mapping tree,cn=config"
        attributes:
          nsds5BeginReplicaRefresh: start
      loop: "{{ list_of_consumers }}"
      loop_control:
        loop_var: consumer
```

and for all necessary agrement (if both mode, only on 1 supplier)
