### ISSUE TITLE
tasks/configure_changelog.yml

### ISSUE THREAD

**Issue by doczkal** [lvps/389ds-replication#7]
I can't get what 3e67ddff18917ceb39379be9c689ced35c065eac tries to accomplish.
The when statements is: when: "ansible_facts['distribution_major_version'] | int >= 8"
Which AFAIK says that the block should run if distribution_major_version is greater or equal 8. But the commit message says:  fix(): do not use changelog5 on RHEL8 and above 
Which is exactly the opposite? I stumbled over this because the block is executed on my centos 8 stream.

Furthermore does the task use item.name and item.value but no item is defined? Maybe I overlooked something?

**Comment by lvps** [comment]
Unfortunately I have no idea what is the correct behavior here.
@rgroux, since you created that commit, do you know if changelog5 should be used there or not? Thanks

**Comment by rgroux** [comment]
i am sorry, yes the `when` conditional should be "<=" ans not ">=".

i don't know how i did this mistake, do you want me to do a patch or do you want to do the patch.
